### ISSUE TITLE
Error setting up on latest version of MSYS2

### ISSUE THREAD

**Issue by superp00t** [richardwilkes/cef#1]
```bash
jjj@jjj-PC MSYS /d/.golang/src/github.com/richardwilkes/cef
$ go run main.go install
Windows is only supported through the use of MINGW64
exit status 1
```

OS: Windows 7
Architecture: x86_64
$MSYSTEM: "MSYS"

**Comment by richardwilkes** [comment]
You must be running inside a MINGW64 shell, not a MSYS2 shell

**Comment by superp00t** [comment]
Thanks for getting back to me so quickly! I was able to successfully install the requisite headers, but then I ran into this error when attempting to compile webapp-example.

```
jjj@jjj-PC MINGW64 /d/.golang/src/github.com/richardwilkes/cef
$ go install github.com/richardwilkes/webapp-example
# github.com/richardwilkes/cef/cef
In file included from ./AccessibilityHandler_gen.h:7,
                 from cef\AccessibilityHandler_gen.go:6:
./capi_gen.h:8:10: fatal error: include/capi/cef_accessibility_handler_capi.h: No such file or directory
 #include "include/capi/cef_accessibility_handler_capi.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

**Comment by richardwilkes** [comment]
It looks like you didn't do a full install. Also, you can't just use `go install`, as some other steps are needed. Try this:

```
go get -u github.com/richardwilkes/cef
cef install
go get -u github.com/richardwilkes/webapp-example
cd $GOPATH/src/github.com/richardwilkes/webapp-example
./build.sh
```

**Comment by superp00t** [comment]
After running those commands, I get the same error.

/usr/local/cef seems to be full of files. however. Perhaps the issue is that "include/capi/cef_accessibility_handler_capi.h" is a relative path and has no way to find the files located in /usr/local/cef/?

**Comment by richardwilkes** [comment]
It sounds like the CEF stuff isn't installed correctly. You may need to remove it from /usr/local and try `cef install` again, as that installs, among other things, a file that tells pkgconfig where to find the headers and libraries.

**Comment by superp00t** [comment]
The problem appears to have been a outdated file, /mingw64/lib/pkgconfig/cef.pc.

I removed that, but  I had to copy the pc file from /lib/pkgconfig/cef.pc to /mingw64/lib/pkgconfig/cef.pc.

Now after successfully building webapp-example, I cannot run dist/windows/example.exe.

```
jjj@jjj-PC MINGW64 /d/.golang/src/github.com/richardwilkes/webapp-example
$ ./dist/windows/example.exe
panic: Failed to load shcore.dll: The specified module could not be found.

goroutine 1 [running, locked to thread]:
syscall.(*LazyProc).mustFind(0xc0000691d0)
        D:/msys2/mingw64/lib/go/src/syscall/dll_windows.go:280 +0x5f
syscall.(*LazyProc).Call(0xc0000691d0, 0xc000050900, 0x4, 0x4, 0x4, 0x6e8d60, 0x7bad01, 0xc000052904)
        D:/msys2/mingw64/lib/go/src/syscall/dll_windows.go:301 +0x36
github.com/richardwilkes/webapp/internal/windows.GetDpiForMonitor(0x10001, 0xc000000000, 0xc000052900, 0xc000052904, 0x32, 0xc0000824c0)
        D:/.golang/src/github.com/richardwilkes/webapp/internal/windows/shcoredll_windows.go:17 +0x89
github.com/richardwilkes/webapp/internal/windows.(*driver).Displays.func1(0x10001, 0x0, 0x22fcd8, 0x0, 0x8)
        D:/.golang/src/github.com/richardwilkes/webapp/internal/windows/displays_windows.go:20 +0x147
github.com/richardwilkes/webapp/internal/windows.EnumDisplayMonitors.func1(0x10001, 0x0, 0x22fcd8, 0x0, 0x100)
        D:/.golang/src/github.com/richardwilkes/webapp/internal/windows/user32dll_windows.go:183 +0x54
syscall.Syscall6(0x77025c30, 0x4, 0x0, 0x0, 0x45ec85, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        D:/msys2/mingw64/lib/go/src/runtime/syscall_windows.go:185 +0xfc
syscall.(*Proc).Call(0xc00004cd60, 0xc0000508c0, 0x4, 0x4, 0x20, 0x6f00c0, 0x1, 0xc0000508c0)
        D:/msys2/mingw64/lib/go/src/syscall/dll_windows.go:152 +0x39d
syscall.(*LazyProc).Call(0xc000069470, 0xc0000508c0, 0x4, 0x4, 0x40da7f, 0x10, 0x715520, 0x437101)
        D:/msys2/mingw64/lib/go/src/syscall/dll_windows.go:302 +0x66
github.com/richardwilkes/webapp/internal/windows.EnumDisplayMonitors(0x0, 0x0, 0xc000046e50, 0x0, 0x0, 0x0)
        D:/.golang/src/github.com/richardwilkes/webapp/internal/windows/user32dll_windows.go:182 +0xdb
github.com/richardwilkes/webapp/internal/windows.(*driver).Displays(0x9940c0, 0xc000079ea8, 0xc000000000, 0x4048b2)
        D:/.golang/src/github.com/richardwilkes/webapp/internal/windows/displays_windows.go:12 +0xd5
github.com/richardwilkes/webapp.Displays(0x62efd4, 0x66f610, 0xc000079ea8)
        D:/.golang/src/github.com/richardwilkes/webapp/display.go:27 +0x3c
github.com/richardwilkes/webapp.MainDisplay(0xc000079ed0)
        D:/.golang/src/github.com/richardwilkes/webapp/display.go:17 +0x29
main.finishStartup()
        D:/.golang/src/github.com/richardwilkes/webapp-example/main.go:35 +0x2d
github.com/richardwilkes/webapp/internal/windows.(*driver).PrepareForEventLoop(0x9940c0)
        D:/.golang/src/github.com/richardwilkes/webapp/internal/windows/app_windows.go:61 +0x2e
github.com/richardwilkes/webapp.Start(0xc00007a040, 0x0, 0x0, 0x0, 0x0)
        D:/.golang/src/github.com/richardwilkes/webapp/start.go:54 +0xee
main.main()
        D:/.golang/src/github.com/richardwilkes/webapp-example/main.go:30 +0x18e
```

Apparently package webapp requires shcore.dll, which is not available on Windows 7.

[I have created a PR on the webapp repository fixing this.](https://github.com/richardwilkes/webapp/pull/2)
